Use a shared ipam namespace by default.
nexodus-io/nexodus pull request #1007
Opened 2023-05-11 12:10 UTC by chirino

* Also switch to the CG-NAT cird 100.64.0.0/10
* Set org `private_cider=true` to use a non-shared ipam namespace for the org.

2023-05-11 12:17 UTC, russellb commented
blocked on merging design proposal in #998

2023-05-11 12:19 UTC, russellb commented
s/cider/cidr/ in the commit message :)

2023-05-11 22:45 UTC, nerdalert commented
Ran it through QA a couple of times 🟢 
https://github.com/nexodus-io/nexodus/actions/runs/4951380705
https://github.com/nexodus-io/nexodus/actions/runs/4952463061

2023-06-09 22:32 UTC, russellb commented
I posted #1168 for a seg fault I saw in the last e2e test run on here.

2023-06-14 16:39 UTC, russellb requested changes
fairly minor comments. This was much simpler than I expected.

2023-06-15 18:14 UTC, nerdalert approved these changes
LGTM, leaving the ability to spin up a custom CIDR addresses my only hesitation with `--cidr 100.100.0.0/16 --cidr-v6 200::/32`.

That coupled with the ability for a user to choose what org a device joins gives the enterprise deployment freedom to customize divisions that aren't SaaS deployments and would prefer sequential addressing for ease in policy etc.

2023-06-16 17:21 UTC, chirino commented
> LGTM, leaving the ability to spin up a custom CIDR addresses my only hesitation with --cidr 100.100.0.0/16 --cidr-v6 200::/32.

Not sure what you mean. This pull request supports doing that.

2023-06-16 17:33 UTC, russellb commented
> > LGTM, leaving the ability to spin up a custom CIDR addresses my only hesitation with --cidr 100.100.0.0/16 --cidr-v6 200::/32.
> 
> Not sure what you mean. This pull request supports doing that.

I was wondering if the response was just misworded a bit. I interpreted it as "this looks good. Maintaining the ability use custom CIDRs resolved my only hesitation."

2023-06-16 18:35 UTC, nerdalert commented
> > LGTM, leaving the ability to spin up a custom CIDR addresses my only hesitation with --cidr 100.100.0.0/16 --cidr-v6 200::/32.
> 
> Not sure what you mean. This pull request supports doing that.

@russellb @chirino Sorry, meant my only reservation was addressed with that. I'm a go here!

2023-06-20 21:31 UTC, chirino commented on internal/database/database.go
> +	"github.com/nexodus-io/nexodus/internal/database/migration_20230509_0000"
Yeah... Maybe we should all switch to InteliJ 😆

2023-06-20 22:18 UTC, chirino commented on integration-tests/security_group_test.go
> +		helper.createSecurityRule("icmpv6", "0", "0", []string{"200::1-200:1::50"}),
I'll change it... but I wonder what we should be seeing in tests that configure bad rules like this...

2023-06-20 22:18 UTC, chirino commented on internal/handlers/organization.go
> +	}
ok

2023-06-20 23:46 UTC, russellb commented on integration-tests/security_group_test.go
> +		helper.createSecurityRule("icmpv6", "0", "0", []string{"200::1-200:1::50"}),
The rule isn't necessarily invalid. You can configure any IP range as long as it's a valid IP range. It's just that I knew this extended beyond the range of what nexodus would ever allocate.

2023-06-20 23:48 UTC, russellb commented on internal/database/database.go
> +	"github.com/nexodus-io/nexodus/internal/database/migration_20230509_0000"
If this change was InteliJ trying to be smart, then I'll definitely pass. 😆

2023-06-21 14:07 UTC, russellb commented
@chirino looks OK, but unit tests are busted

2023-06-22 15:18 UTC, merged