Add a retry to failed STUN lookups on initilization
nexodus-io/nexodus pull request #1045
Opened 2023-05-19 01:11 UTC by nerdalert

- Adds a retry to symmetricNatDisco() in case one of the two lookups fail.
- Adds a log message if a node is Symmetric but the org does have a relay.
- Issue #1043

2023-05-19 02:58 UTC, russellb reviewed
a couple of thoughts / questions:

1) I believe symmetricNatDisco() only called once at startup. so we don't currently detect if a device moves between symmetric and not-symmetric? Is there an issue on this already, or am I thinking about it wrong?

2) Adding more retries will make startup hang for longer on a network where stun is blocked. I guess that's not a big deal right now because it's not going to work anyway if stun doesn't work. Prior to this change, it'll at least error out and give you an error after a minute or so. With this change it's going to hang for much longer before logging any errors. Maybe if it at least logged an error (or warning?) every time a stun request failed, it will at least still give an indication about why it's hanging. 

This reminds me of #1044. When behind symmetric NAT, we need to get our NAT binding from the relay, not STUN. Once that's working, it's the same thing in the case of stun being blocked. nexd should still work with a relay (as long as udp isn't blocked all together). In other words, if stun keeps failing, at some point I think nexd should fall back to concluding we have to assume it's Symmetric NAT. We still have a chance of getting working connectivity there, but not if we're stuck on stun.

What do you think?

2023-05-19 02:59 UTC, russellb requested changes
meant to hit "Request changes"

2023-05-24 00:01 UTC, nerdalert commented
@russellb I backed down the retryTimer here to 1 second so it will take less time on startup. This also helps with a false positive if one stun doesn't return anything it will attempt to get an accurate return from both. The blocking is definitely not ideal and might be worth re-implementing the STUN lookup with a done timer channel at some point.

2023-05-25 14:51 UTC, russellb commented
> @russellb I backed down the retryTimer here to 1 second so it will take less time on startup. This also helps with a false positive if one stun doesn't return anything it will attempt to get an accurate return from both. The blocking is definitely not ideal and might be worth re-implementing the STUN lookup with a done timer channel at some point. Ty for the review.

Thanks for the updates. This lgtm.

2023-05-25 14:52 UTC, russellb approved these changes

2023-05-25 14:52 UTC, merged