Switching device registration log based on revision
nexodus-io/nexodus pull request #1211
Opened 2023-06-22 07:53 UTC by akoserwal

Addressing: https://github.com/nexodus-io/nexodus/issues/1063

2023-06-22 12:18 UTC, russellb requested changes
Thanks for looking at this!

2023-06-22 12:18 UTC, russellb commented on internal/nexodus/nexodus.go
> +	if modelsDevice.Revision != 0 && modelsDevice.Revision > 1 {
```suggestion
	if modelsDevice.Revision > 1 {
```

You can drop the first check. It's redundant with the second one.

2023-06-22 18:07 UTC, chirino requested changes
You can't use revision to detect if it's the first restoration of a device.

2023-06-26 09:17 UTC, akoserwal commented on internal/nexodus/nexodus.go
> +		deviceRegLogMsg = "Reconnected as device"
@chirino is there any other field which I can use?

2023-06-26 17:17 UTC, chirino commented on internal/nexodus/nexodus.go
> +		deviceRegLogMsg = "Reconnected as device"
see the implementation of `createOrUpdateDeviceOperation` you could have it return another value indicating if the device was created or it had existed.

2023-06-27 16:32 UTC, chirino approved these changes
LGTM

2023-06-30 13:00 UTC, russellb approved these changes

2023-06-30 13:01 UTC, merged