Add token refresh to client side web ui
nexodus-io/nexodus pull request #1463
Opened 2023-09-25 19:36 UTC by nerdalert

- This should resolve the hard logout after the initial token expires after 300s. The logic is the OIDC token Refresh() kicks off 5sec before the exp in the keycloak token is set to expire and gets updated with a new refresh token. More details on this method at: https://marmelab.com/blog/2020/07/02/manage-your-jwt-react-admin-authentication-in-memory.html
- Tokens are still managed on the server-side so the client side is not dealing with storage. There are pros and cons for both methods.
- Safari private-mode is the only scenario that doesn't work here, but Safari is notorious for its strictness in cookies so it is likely something related.

2023-09-25 19:36 UTC, nerdalert commented
Putting on hold until tomorrow to let client sides run overnight to see if there are any long running issues.

2023-09-25 20:11 UTC, russellb requested changes

2023-09-25 20:11 UTC, russellb commented on internal/api/public/api_auth.go
> +		}
```suggestion
		if localVarHTTPResponse.StatusCode == 400 || localVarHTTPResponse.StatusCode == 401 || localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
```

2023-09-25 20:11 UTC, russellb commented on internal/api/public/api_auth.go
> +		}
```suggestion
		if localVarHTTPResponse.StatusCode == 401 || localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
```

2023-09-25 20:11 UTC, russellb commented on internal/api/public/api_auth.go
> +		}
```suggestion
		if localVarHTTPResponse.StatusCode == 401 || localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
```

2023-09-26 01:29 UTC, nerdalert commented on internal/api/public/api_auth.go
> +		}
@russellb Ahoy! Those are all openapi generated files.

2023-09-26 13:49 UTC, russellb commented on internal/api/public/api_auth.go
> +		}
@nerdalert lol sorry.

2023-09-26 13:50 UTC, russellb approved these changes

2023-09-27 17:29 UTC, merged